event_no: '20200801'
job_id: example_job
pbs_id: null
pbs_script: Hydrojob.pbs
period:
  end: 2020-01-02 20:00:00
  start: 2020-01-01 00:00:00
raw_run_dir: F:/Haihe/Run/wrfhydro_runner/run_source\20200801
result_dir: F:/Haihe/Run/wrfhydro_runner/result
run_dir: F:/Haihe/Run/wrfhydro_runner/run
set_params:
  MannN: 0.5
  SLOPE: 0.1
  SMCMAX: 0.2
wrfhydrofrxst: frxst_pts_out.txt
